version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "Click"
      - match:
          dependency_name: "Sphinx"
      - match:
          dependency_name: "sphinx-click"
      - match:
          dependency_name: "sphinxcontrib-websupport"
      - match:
          dependency_name: "coveralls"
      - match:
          dependency_name: "coverage"
      - match:
          dependency_name: "pytest"
      - match:
          dependency_name: "pytest-cov"
      - match:
          dependency_name: "twine"
      - match:
          dependency_name: "setuptools"
      - match:
          dependency_name: "importlib-metadata"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
